### ISSUE TITLE
It's not returning anything

### ISSUE THREAD

**Issue by westlakem** [sbkwgh/preview-link#2]
EXPRESS CODE: 

```
app.get('/api/link-preview', async (req, res) => {
  console.log('url', 'https://www.github.com');
  previewLink('https://www.github.com').then(html => {
    console.log('preview', html);
    res.send(html);
  })
    .catch(err => {
      console.log('error', err)
    })
});
```
CONSOLE LOG

```
url https://www.github.com
preview

```

EDIT:

Looking at my client that makes the api request, the response is `null`

**Comment by sbkwgh** [comment]
This is probably because of rate-limiting from github

I've updated the api to better handle errors like this (see the updated README) - in the future I'll add some form of caching too
